modifyLineBreaks:
  textWrapOptions:
    columns: 80
    blocksFollow:
      other: '\\start[a-zA-Z]+(?>\[.*\])?'
    blocksBeginWith:
      other: '\\(?!start|stop)[a-zA-Z]+|\\\(|\{|-|\.|"'
    blocksEndBefore:
      other: '\\stop[a-zA-Z]*'
